#!/bin/bash
# Description: Sets the PostgreSQL environment for scripts and console users
#

export APPLIANCE_PG_CTL=/usr/pgsql-9.4/bin/pg_ctl
export APPLIANCE_PG_DATA=/var/lib/pgsql/9.4-bdr/data
export APPLIANCE_PG_SERVICE=postgresql-9.4
export APPLIANCE_PG_PACKAGE_NAME=postgresql-bdr94-server-9.4.5_bdr1-1_2ndQuadrant
export PATH=$PATH:/usr/pgsql-9.4/bin
